# a sample compose file
version: '3'
services:
  nodealpine:
    build:
      context: ./compose/refined_image
      args:
       - BASEIMAGE=${FIRST_BASE_IMAGE}
    image: ${FIRST_REFINED_IMAGE_ROOT}:${STACK_VERSION}
    container_name: ${STACK_NAME:-defstack}_nodealpine
    ports:
     - 8088:5000
    networks:
     - mydefaultstack
    environment:
     - BLA=0.0.0.0
    volumes:
     - ./compose/refined_image/app/index.js:/usr/src/app/index.js

networks:
  mydefaultstack:
    name: mydefaultstack
    external: true
