# a sample compose file
version: '3'
services:
  nodealpine:
    build:
      context: ./compose/refined_image
      args:
        - BASEIMAGE=${FIRST_BASE_IMAGE}
    image: ${FIRST_REFINED_IMAGE_ROOT}:${STACK_VERSION}
    container_name: ${STACK_NAME:-defstack}_nodealpine
    env_file: .env
    ports:
      - 8088:${NODE_SERVER_PORT}
    networks:
      - mydefaultstack
    environment:
      - PORT=${NODE_SERVER_PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodealpine.tls=true"
      - "traefik.http.routers.nodealpine.rule=Host(`node.${DOMAIN_NAME}`)"
      - "traefik.http.services.nodealpine.loadbalancer.server.port=${NODE_SERVER_PORT}"
    volumes:
      - ./compose/refined_image/my_app/src:/usr/src/app/src:ro
      - ./compose/refined_image/my_app/public:/usr/src/app/public:ro

networks:
  mydefaultstack:
    name: mydefaultstack
    external: true
